server:
   port: 9950
spring:
   profiles:
      active: dev
hbase:
   config:
      hbase.zookeeper.quorum: 192.168.209.129
      hbase.zookeeper.port: 2181
      hbase.zookeeper.znode: /hbase
      hbase.client.keyvalue.maxsize: 1572864000



